leftnav:
- identifier: cd8bbc39-20c2-c2d6-e737-08dbcee1b5bb
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: faa3bb78-91b7-2614-585d-2a7ca7cd8711
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: e7710e71-d58f-7e19-3751-8fe133d42432
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: cf58407a-2c2b-3892-6cb5-9cc75c2a27e8
  name: Recitations
  url: /pages/recitations
  weight: 40
- identifier: db2852ac-ede0-e08a-3433-5e0619171a6e
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 87675643-1069-c50d-de8b-1a57f278badd
  name: Exams
  url: /pages/exams
  weight: 60
